version: '3.7'

services:
  test_pg:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: eliftech
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "4041:5432"
    volumes:
      - test_pg:/var/lib/postgresql/data

  test_pg_pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "4042:8080"
    environment:
      PGADMIN_DEFAULT_EMAIL: username@example.com
      PGADMIN_DEFAULT_PASSWORD: password

volumes:
  test_pg: